apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deploy-deployment
  labels:
    app: springboot-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-deploy
  template:
    metadata:
      labels:
        app: springboot-deploy
    spec:
      containers:
      - name: springboot-container
        image: springboot-deploy:34
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-deploy-service
spec:
  selector:
    app: springboot-deploy
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

